const colors: any = [
    { code: "563", name: "Acqua" },
    { code: "596", name: "Acqua Fosco" },
    { code: "537", name: "Algodão Doce" },
    { code: "539", name: "Algodão Doce Fosco" },
    { code: "556", name: "Beach" },
    { code: "575", name: "Beach Fosco" },
    { code: "551", name: "Bloom" },
    { code: "584", name: "Bloom Fosco" },
    { code: "008", name: "Branco" },
    { code: "488", name: "Branco Fosco" },
    { code: "572", name: "Cherry" },
    { code: "744", name: "Cherry Fosco" },
    { code: "554", name: "Ciment" },
    { code: "577", name: "Ciment Fosco" },
    { code: "514", name: "Cinza Claro" },
    { code: "477", name: "Cinza Claro Fosco" },
    { code: "515", name: "Cinza Escuro" },
    { code: "478", name: "Cinza Escuro Fosco" },
    { code: "528", name: "Coconut" },
    { code: "541", name: "Coconut Fosco" },
    { code: "534", name: "Doce de Leite" },
    { code: "618", name: "Doce de Leite Fosco" },
    { code: "538", name: "Green" },
    { code: "578", name: "Green Fosco" },
    { code: "531", name: "Jeans" },
    { code: "550", name: "Jeans Fosco" },
    { code: "721", name: "Linho" },
    { code: "725", name: "Linho Fosco" },
    { code: "086", name: "Marrom" },
    { code: "481", name: "Marrom Fosco" },
    { code: "530", name: "Militar" },
    { code: "545", name: "Militar Fosco" },
    { code: "720", name: "Náutico" },
    { code: "727", name: "Náutico Fosco" },
    { code: "532", name: "Naval" },
    { code: "544", name: "Naval Fosco" },
    { code: "776", name: "Neve" },
    { code: "777", name: "Neve Fosco" },
    { code: "553", name: "Niquel" },
    { code: "597", name: "Niquel Fosco" },
    { code: "719", name: "Off" },
    { code: "726", name: "Off Fosco" },
    { code: "525", name: "Papaya" },
    { code: "617", name: "Papaya Fosco" },
    { code: "036", name: "Preto" },
    { code: "485", name: "Preto Fosco" },
    { code: "548", name: "Rosa Chá" },
    { code: "599", name: "Rosa Chá Fosco" },
    { code: "526", name: "Terracota" },
    { code: "542", name: "Terracota Fosco" },
    { code: "464", name: "Brown" },
    { code: "482", name: "Brown Fosco" },
    { code: "245", name: "Champagne" },
    { code: "487", name: "Champagne Fosco" },
    { code: "432", name: "Chumbo" },
    { code: "517", name: "Chumbo Fosco" },
    { code: "362", name: "Dourado" },
    { code: "588", name: "Dourado Fosco" },
    { code: "451", name: "Gold" },
    { code: "480", name: "Gold Fosco" },
    { code: "491", name: "Grafite" },
    { code: "492", name: "Grafite Fosco" },
    { code: "604", name: "Honey" },
    { code: "707", name: "Honey Fosco" },
    { code: "473", name: "Madrepérola" },
    { code: "484", name: "Madrepérola Fosco" },
    { code: "361", name: "Pérola" },
    { code: "483", name: "Pérola Fosco" },
    { code: "508", name: "Prata Lunar" },
    { code: "512", name: "Prata Lunar Fosco" },
    { code: "509", name: "Rosa Claro Pérola" },
    { code: "513", name: "Rosa Claro Pérola Fosco" },
    { code: "755", name: "Ametista" },
    { code: "756", name: "Ametista Fosco" },
    { code: "639", name: "Aquamarine" },
    { code: "745", name: "Aquamarine Fosco" },
    { code: "083", name: "Conhaque" },
    { code: "600", name: "Conhaque Fosco" },
    { code: "012", name: "Cristal" },
    { code: "589", name: "Cristal Fosco" },
    { code: "021", name: "Fumê" },
    { code: "586", name: "Fumê Fosco" },
    { code: "757", name: "Safira" },
    { code: "758", name: "Safira Fosco" },
    { code: "751", name: "Topázio" },
    { code: "752", name: "Topázio Fosco" },
    { code: "753", name: "Turmalina" },
    { code: "754", name: "Turmalina Fosco" },
    { code: "047", name: "Verde Turq." },
    { code: "786", name: "Verde Turq. Fosco" },
    { code: "199", name: "Violeta Claro" },
    { code: "787", name: "Violeta Claro Fosco" },
    { code: "778", name: "Cristal Fosco/Algodão Doce" },
    { code: "715", name: "Cristal Fosco/Beach" },
    { code: "723", name: "Cristal Fosco/Ciment" },
    { code: "779", name: "Cristal Fosco/Cinza Claro" },
    { code: "718", name: "Cristal Fosco/Coconut" },
    { code: "780", name: "Cristal Fosco/Esmeralda" },
    { code: "781", name: "Cristal Fosco/Honey" },
    { code: "782", name: "Cristal Fosco/Jade" },
    { code: "775", name: "Cristal Fosco/Linho" },
    { code: "627", name: "Cristal Fosco/Marrom" },
    { code: "730", name: "Cristal Fosco/Militar" },
    { code: "785", name: "Cristal Fosco/Náutico" },
    { code: "628", name: "Cristal Fosco/Naval" },
    { code: "583", name: "Cristal Fosco/Ouro" },
    { code: "722", name: "Cristal Fosco/Pérola" },
    { code: "625", name: "Cristal Fosco/Prata" },
    { code: "606", name: "Cristal Fosco/Preto" },
    { code: "590", name: "Cristal Fosco/Red Gold" },
    { code: "748", name: "Cristal Fosco/Rosa Chá" },
    { code: "629", name: "Cristal/Algodão Doce" },
    { code: "710", name: "Cristal/Beach" },
    { code: "624", name: "Cristal/Ciment" },
    { code: "738", name: "Cristal/Cinza Claro" },
    { code: "622", name: "Cristal/Coconut" },
    { code: "636", name: "Cristal/Esmeralda" },
    { code: "740", name: "Cristal/Honey" },
    { code: "742", name: "Cristal/Jade" },
    { code: "737", name: "Cristal/Linho" },
    { code: "250", name: "Cristal/Marrom" },
    { code: "698", name: "Cristal/Militar" },
    { code: "749", name: "Cristal/Náutico" },
    { code: "623", name: "Cristal/Naval" },
    { code: "241", name: "Cristal/Ouro" },
    { code: "637", name: "Cristal/Pérola" },
    { code: "242", name: "Cristal/Prata" },
    { code: "247", name: "Cristal/Preto" },
    { code: "449", name: "Cristal/Red Gold" },
    { code: "635", name: "Cristal/Rosa Chá" },

    { code: "056", name: "Black Matte", finish: "Deca" },
    { code: "052", name: "Gold", finish: "Deca" },
    { code: "055", name: "Gold Matte", finish: "Deca" },
    { code: "054", name: "Red Gold", finish: "Deca" },
    { code: "076", name: "Ouro Esc.", finish: "Docol" },
    { code: "051", name: "Cromado", finish: "Resimetal" },
    { code: "072", name: "Acrilico Branco" },
    { code: "070", name: "Acrilico Cristal" },
    { code: "071", name: "Acrilico Preto" }
];

export default colors;

